# Generated by Django 3.0.3 on 2020-03-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
