# Generated by Django 3.0.3 on 2020-03-15 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0004_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Societies'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
