# Generated by Django 3.0.3 on 2020-03-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socshare', '0005_auto_20200315_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
        migrations.AddField(
            model_name='society',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
