# Generated by Django 3.0.3 on 2020-03-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0006_auto_20200322_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
