# Generated by Django 3.0.3 on 2020-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0008_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
