# Generated by Django 3.0.3 on 2020-03-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0009_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='picture',
        ),
        migrations.AddField(
            model_name='society',
            name='banner',
            field=models.ImageField(default='test.png', upload_to='events_banners'),
        ),
        migrations.AddField(
            model_name='society',
            name='profile',
            field=models.ImageField(default='default.png', upload_to='profile'),
        ),
    ]
