# Generated by Django 3.0.3 on 2020-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0010_auto_20200326_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='profile',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
    ]
