# Generated by Django 3.0.3 on 2020-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0011_auto_20200326_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_short',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
