# Generated by Django 3.0.3 on 2020-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0013_auto_20200326_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='banner',
            field=models.ImageField(default='default.png', upload_to='profile_banner'),
        ),
    ]
