# Generated by Django 3.0.3 on 2020-03-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socshare', '0016_auto_20200331_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='token',
            new_name='auth',
        ),
    ]
